#!/usr/bin/env python3
"""Build the browser compatibility runtime without external tooling.

The source remains split under js/core, js/ui and js/utils. This script emits:
- js/runtime-data.js: static data bundle for file:// and restrictive browsers
- js/app.bundle.js: classic-script bundle, avoiding ES-module loading/CORS issues
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JS = ROOT / "js"
DATA = ROOT / "assets" / "data"

SOURCES = [
    "utils/compat.js",
    "utils/math.js",
    "utils/export.js",
    "core/electrochem.js",
    "core/ecm.js",
    "core/thermal.js",
    "core/degradation.js",
    "core/pack.js",
    "core/vehicle.js",
    "core/simulator.js",
    "ui/i18n.js",
    "ui/charts.js",
    "ui/cell-visualization.js",
    "ui/pack-visualization.js",
    "ui/app-view.js",
    "main.js",
]


def build_runtime_data() -> None:
    payload = {
        "cellPresets": json.loads((DATA / "cell-presets.json").read_text(encoding="utf-8")),
        "modelPriors": json.loads((DATA / "model-priors.json").read_text(encoding="utf-8")),
        "us06": json.loads((DATA / "us06.json").read_text(encoding="utf-8")),
        "nmcReference": json.loads((DATA / "nmc-reference-1c.json").read_text(encoding="utf-8")),
    }
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    (JS / "runtime-data.js").write_text(
        "/* Generated from assets/data. Do not edit by hand. */\n"
        "window.EVBS_RUNTIME_DATA=" + body + ";\n",
        encoding="utf-8",
    )


def module_to_classic(source: str) -> str:
    lines = []
    for line in source.splitlines():
        if re.match(r"^\s*import\s+", line):
            continue
        if re.match(r"^\s*export\s*\{", line):
            continue
        line = re.sub(r"^(\s*)export\s+(?=(class|function|const|let|var)\b)", r"\1", line)
        lines.append(line)
    return "\n".join(lines)


def build_classic_bundle() -> None:
    chunks = [
        "/* EV Battery Sim compatibility bundle. Generated by scripts/build_runtime.py. */",
        "(function(){",
        "'use strict';",
    ]
    for relative in SOURCES:
        source = (JS / relative).read_text(encoding="utf-8")
        chunks.append("\n/* source: js/%s */\n%s\n" % (relative, module_to_classic(source)))
    chunks.append("})();\n")
    (JS / "app.bundle.js").write_text("\n".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    build_runtime_data()
    build_classic_bundle()
    print("Built js/runtime-data.js and js/app.bundle.js")
